export const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg",
      genre_ids: [28, 12, 878],
      id: 670292,
      original_language: "en",
      original_title: "The Creator",
      overview:
        "Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.",
      popularity: 213.145,
      poster_path: "/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg",
      release_date: "2023-09-27",
      title: "The Creator",
      video: false,
      vote_average: 7.1,
      vote_count: 2134,
    },
    {
      adult: false,
      backdrop_path: "/tlNzm03CHTNEXc1mih0obFBYwwx.jpg",
      genre_ids: [878, 28],
      id: 1028725,
      original_language: "zh",
      original_title: "变种人：幽灵战姬",
      overview:
        "Wu Qingqing is an agent of the International Security Alliance (to combat mutant crime) and is ordered to infiltrate Medusa Plastic Hospital to collect evidence of the secret research on genetic induction fluid by its direct consortium to create mutant fighters. Wu Qingqing successfully infiltrates, but was forced to inject a gene induction fluid.",
      popularity: 315.662,
      poster_path: "/ensNfCsxIRIr6LJnrRCXd94tfd.jpg",
      release_date: "2022-09-26",
      title: "Mutant: Ghost War Girl",
      video: false,
      vote_average: 5.222,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: "/zX9m8h33pHXcES7ttO8v0ThiYj7.jpg",
      genre_ids: [18, 28, 53],
      id: 1053592,
      original_language: "es",
      original_title: "Todos los nombres de Dios",
      overview:
        "After being implicated in a terrorist attack, Santi, a taxi driver, is taken hostage by one of the perpetrators.",
      popularity: 186.367,
      poster_path: "/n15gfcgwV0LVPSobrayZcFHcwN6.jpg",
      release_date: "2023-09-15",
      title: "All the Names of God",
      video: false,
      vote_average: 6.6,
      vote_count: 54,
    },
    {
      adult: false,
      backdrop_path: "/tC78Pck2YCsUAtEdZwuHYUFYtOj.jpg",
      genre_ids: [28, 53, 80],
      id: 926393,
      original_language: "en",
      original_title: "The Equalizer 3",
      overview:
        "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
      popularity: 199.653,
      poster_path: "/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg",
      release_date: "2023-08-30",
      title: "The Equalizer 3",
      video: false,
      vote_average: 7.414,
      vote_count: 2199,
    },
    {
      adult: false,
      backdrop_path: "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: "en",
      original_title: "Spider-Man: No Way Home",
      overview:
        "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
      popularity: 201.982,
      poster_path: "/5weKu49pzJCt06OPpjvT80efnQj.jpg",
      release_date: "2021-12-15",
      title: "Spider-Man: No Way Home",
      video: false,
      vote_average: 7.975,
      vote_count: 18951,
    },
    {
      adult: false,
      backdrop_path: "/uBz7ji0Zw3vX99WH31rHFG5X0Az.jpg",
      genre_ids: [28, 18],
      id: 845861,
      original_language: "hi",
      original_title: "State of Siege: Temple Attack",
      overview:
        "Based on the true incident of the 2002 terrorist attack in Gujarat's Akshardham temple, the story revolves around the bravery of NSG commandos, who stood up for their country and their people in the worst of times.",
      popularity: 178.981,
      poster_path: "/ckghAN8FuYY2icUyJjVkKXiBrek.jpg",
      release_date: "2021-07-09",
      title: "State of Siege: Temple Attack",
      video: false,
      vote_average: 6.19,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/46Os8U0DEPmI0OnvKDxucl6SLVZ.jpg",
      genre_ids: [27, 53],
      id: 1008042,
      original_language: "en",
      original_title: "Talk to Me",
      overview:
        "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
      popularity: 175.618,
      poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
      release_date: "2023-07-26",
      title: "Talk to Me",
      video: false,
      vote_average: 7.208,
      vote_count: 2243,
    },
    {
      adult: false,
      backdrop_path: "/jkBFGhuJKLH8VurXqVKQ2mxvVYC.jpg",
      genre_ids: [37],
      id: 1079394,
      original_language: "en",
      original_title: "The Five",
      overview:
        "A scorned woman enlist the help of five strangers to execute a bank robbery. Tensions rise as the men anxiously await her arrival with the money, leaving the crew to wonder if they have been betrayed.",
      popularity: 296.057,
      poster_path: "/xckDPGprPVDpuzhSyo9E7SZJ2wa.jpg",
      release_date: "2023-01-07",
      title: "The Five",
      video: false,
      vote_average: 7.125,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: "/xFYpUmB01nswPgbzi8EOCT1ZYFu.jpg",
      genre_ids: [12, 28, 18],
      id: 980489,
      original_language: "en",
      original_title: "Gran Turismo",
      overview:
        "The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.",
      popularity: 199.94,
      poster_path: "/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg",
      release_date: "2023-08-09",
      title: "Gran Turismo",
      video: false,
      vote_average: 7.955,
      vote_count: 1901,
    },
    {
      adult: false,
      backdrop_path: "/yF1eOkaYvwiORauRCPWznV9xVvi.jpg",
      genre_ids: [28, 12, 878],
      id: 298618,
      original_language: "en",
      original_title: "The Flash",
      overview:
        "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
      popularity: 221.607,
      poster_path: "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
      release_date: "2023-06-13",
      title: "The Flash",
      video: false,
      vote_average: 6.789,
      vote_count: 3548,
    },
    {
      adult: false,
      backdrop_path: "/lVoHnqwfkDv4GHktEewBguhiNRn.jpg",
      genre_ids: [53, 28, 18],
      id: 1183905,
      original_language: "de",
      original_title: "Trunk - Locked In",
      overview:
        "Malina wakes up disoriented in the trunk of a speeding car and discovers to her horror that she is missing more than her memory. With her mobile phone as the only link to the outside world, she wages a desperate battle for survival.",
      popularity: 290.549,
      poster_path: "/5KYOsr338jGBXfmdUT1prj4ZZW4.jpg",
      release_date: "2023-11-24",
      title: "Trunk: Locked In",
      video: false,
      vote_average: 5.5,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
      genre_ids: [12, 14, 16, 35, 10751, 28],
      id: 315162,
      original_language: "en",
      original_title: "Puss in Boots: The Last Wish",
      overview:
        "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
      popularity: 203.855,
      poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
      release_date: "2022-12-07",
      title: "Puss in Boots: The Last Wish",
      video: false,
      vote_average: 8.25,
      vote_count: 6960,
    },
    {
      adult: false,
      backdrop_path: "/vruRG9oFSC2QI3F6vLAsj1ND14S.jpg",
      genre_ids: [878, 28, 53, 27],
      id: 934194,
      original_language: "en",
      original_title: "Slash/Back",
      overview:
        "In a remote Arctic community, a group of Inuit girls fight off an alien invasion, all while trying to make it to the coolest party in town.",
      popularity: 164.7,
      poster_path: "/fmmRFQtsRrNOpmcfoxVIyE1LxxT.jpg",
      release_date: "2022-06-24",
      title: "Slash/Back",
      video: false,
      vote_average: 6.5,
      vote_count: 59,
    },
    {
      adult: false,
      backdrop_path: "/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg",
      genre_ids: [12, 28, 878],
      id: 299536,
      original_language: "en",
      original_title: "Avengers: Infinity War",
      overview:
        "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
      popularity: 182.633,
      poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      release_date: "2018-04-25",
      title: "Avengers: Infinity War",
      video: false,
      vote_average: 8.251,
      vote_count: 28399,
    },
    {
      adult: false,
      backdrop_path: "/xzdOIL7261CWehsHOk3lnP0xqam.jpg",
      genre_ids: [28, 878, 12],
      id: 565770,
      original_language: "en",
      original_title: "Blue Beetle",
      overview:
        "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.",
      popularity: 175.843,
      poster_path: "/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
      release_date: "2023-08-16",
      title: "Blue Beetle",
      video: false,
      vote_average: 6.877,
      vote_count: 2129,
    },
    {
      adult: false,
      backdrop_path: "/hRPKfuotMeyRiXXGPKmmrVXD5DG.jpg",
      genre_ids: [28],
      id: 504148,
      original_language: "en",
      original_title: "The Serpent",
      overview:
        "Top special agent Lucinda Kavsky works for a secret part of the CIA. She's given a special assignment but then set up by her own agency.",
      popularity: 167.707,
      poster_path: "/5OSfx8jJrjHWO9SU3Wtfd7Rs8PF.jpg",
      release_date: "2021-01-28",
      title: "The Serpent",
      video: false,
      vote_average: 5.712,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
      genre_ids: [12, 14],
      id: 671,
      original_language: "en",
      original_title: "Harry Potter and the Philosopher's Stone",
      overview:
        "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
      popularity: 196.477,
      poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
      release_date: "2001-11-16",
      title: "Harry Potter and the Philosopher's Stone",
      video: false,
      vote_average: 7.915,
      vote_count: 26066,
    },
    {
      adult: false,
      backdrop_path: "/zgQQF04u3OgNBJqClRNby1FPz9s.jpg",
      genre_ids: [16, 10751, 28, 878, 35, 18, 12],
      id: 893723,
      original_language: "en",
      original_title: "PAW Patrol: The Mighty Movie",
      overview:
        "A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.",
      popularity: 171.688,
      poster_path: "/aTvePCU7exLepwg5hWySjwxojQK.jpg",
      release_date: "2023-09-21",
      title: "PAW Patrol: The Mighty Movie",
      video: false,
      vote_average: 7.071,
      vote_count: 324,
    },
    {
      adult: false,
      backdrop_path: "/mv8M0PqQYicndU7TGgBAHrI4uUo.jpg",
      genre_ids: [27, 53],
      id: 744857,
      original_language: "es",
      original_title: "Cuando acecha la maldad",
      overview:
        "Residents of a small rural town discover that a demon is about to be born among them. They desperately try to escape before the evil is born, but it may be too late.",
      popularity: 150.5,
      poster_path: "/2gimJ06p9tVR4P6jacZWcLcNEwA.jpg",
      release_date: "2023-10-05",
      title: "When Evil Lurks",
      video: false,
      vote_average: 7.378,
      vote_count: 504,
    },
    {
      adult: false,
      backdrop_path: "/4MUfDtBqUFqotGF5RJOfNfoBTLo.jpg",
      genre_ids: [28, 27, 14],
      id: 951546,
      original_language: "en",
      original_title: "Reign of Chaos",
      overview:
        "When the world is gripped by a plague unleashed by the evil lord Chaos, and humans are turned into rabid creatures, mankind can only be saved by three young women, descendants of a Goddess, with the power to stop Chaos' evil.",
      popularity: 172.063,
      poster_path: "/nTMmpvR9TyV631tpFr4FtYxG0FC.jpg",
      release_date: "2022-04-12",
      title: "Reign of Chaos",
      video: false,
      vote_average: 5.7,
      vote_count: 36,
    },
  ],
  total_pages: 42661,
  total_results: 853211,
};
